import "server-only";
import os from "node:os";
import path from "node:path";
import { mkdir, rm } from "node:fs/promises";
import { env } from "@/lib/env";

export const ALLOWED_VIDEO_TYPES: Record<string, string> = {
  "video/mp4": "mp4",
  "video/quicktime": "mov",
  "video/webm": "webm",
  "video/x-matroska": "mkv",
  "video/x-msvideo": "avi",
};

export function uploadDir() {
  // Serverless platforms (e.g. Vercel, AWS Lambda) have a read-only root filesystem.
  // Only /tmp is writable. Fall back to /tmp if UPLOAD_DIR is a relative path.
  if (
    (process.env.VERCEL || process.env.AWS_LAMBDA_FUNCTION_NAME) &&
    (!process.env.UPLOAD_DIR || process.env.UPLOAD_DIR.startsWith("."))
  ) {
    return path.join(os.tmpdir(), "tubepilot-uploads");
  }
  // Runtime-configured directory; tell Turbopack not to trace it into the build output.
  return path.resolve(/*turbopackIgnore: true*/ process.cwd(), env().UPLOAD_DIR);
}

export async function ensureUploadDir() {
  await mkdir(uploadDir(), { recursive: true });
}

/** Absolute path for a stored file. `fileName` is always generated by us, never user input. */
export function videoPath(fileName: string) {
  return path.join(/*turbopackIgnore: true*/ uploadDir(), path.basename(fileName));
}

export async function deleteVideoFile(fileName: string | null | undefined) {
  if (!fileName) return;
  await rm(videoPath(fileName), { force: true }).catch((err) =>
    console.error("[storage] failed to delete", fileName, err),
  );
}
